name: CI/CD pipeline básico

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build con Maven
        working-directory: 05_devops-automation/pipeline1
        run: mvn clean install

      - name: Ejecutar tests con Maven
        working-directory: 05_devops-automation/pipeline1
        run: mvn test



      - name: Build Docker image
        working-directory: 05_devops-automation/pipeline1
        run: docker build -t my-app:${{ github.sha }} .






