name: CI/CD pipeline completo

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar con Maven
        working-directory: 05_devops-automation/pipeline1
        run: mvn clean install

      - name: Ejecutar pruebas con Maven
        working-directory: 05_devops-automation/pipeline1
        run: mvn test

      - name: Construir imagen Docker
        working-directory: 05_devops-automation/pipeline1
        run: docker build -t my-app:${{ github.sha }} .

      - name: Login a DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Etiquetar y subir imagen a DockerHub
        working-directory: 05_devops-automation/pipeline1
        run: |
          docker tag my-app:${{ github.sha }} rodolfodev/my-app:latest
          docker push rodolfodev/my-app:latest










